CREATE DATABASE IF NOT EXISTS LP1;
USE LP1;

CREATE TABLE IF NOT EXISTS Cachorro (
    id INT AUTO_INCREMENT PRIMARY KEY,
    raca VARCHAR(100),
    numeroPatas INT,
    corDoPelo VARCHAR(100)
);

CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'root';

GRANT ALL PRIVILEGES ON LP1.* TO 'root'@'localhost';

FLUSH PRIVILEGES;
